Repository microsoft/mu_common_intel_min_platform, pull requests merged in 2024-01, with the labels that each got.

#230 Removed references to openssllib and it's associated libraries
  MinPlatformPkg/Include/Dsc/CoreCommonLib.dsc
  MinPlatformPkg/Include/Dsc/CoreDxeLib.dsc
  MinPlatformPkg/Include/Dsc/CorePeiLib.dsc
Labels: impact:non-functional

#237 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional

#232 Updated CISettings.py to use the edk2toolext codeql helpers
  .github/workflows/codeql.yml
  .pytool/CISettings.py
Labels: impact:testing, impact:non-functional
